Repository w3c/epub-specs, pull requests merged in 2021-05, with the labels that each got.

#1647 Group non characters in character restrictions
  epub33/core/index.html
Labels: i18n-tracker

#1656 Security and Privacy Questionnaire Rough Draft
  epub33/explainers/EPUB-33-security-privacy.md
  epub33/explainers/EPUB33-explainer.md
Labels: Cat-Security

#1655 Complete rewrite of section on prefixed CSS properties
  epub33/core/index.html
Labels: Cat-CSS, Spec-CSS

#1671 Added the text on requiring common origin
  epub33/rs/index.html
Labels: Agenda+
