Repository w3c/epub-specs, pull requests merged in 2021-04, with the labels that each got.

#1598 Add onix and marc21 as examples of record formats
  epub33/a11y/index.html
  epub33/common/js/biblio.js
Labels: Cat-Accessibility

#1468 Clarify base iri of package document
  epub33/core/index.html
  epub33/rs/index.html
Labels: Status-NeedsDiscussion

#1615 Fixing issue in 1611
  epub33/rs/index.html
Labels: Type-Editorial

#1620 User interaction may overwrite CSS
  epub33/rs/index.html
Labels: Spec-ReadingSystems

#1617 Remove the explicit list of implementations from the media type specs
  epub33/core/index.html
Labels: Type-Editorial

#1616 Handled the mega-issue 1612
  epub33/rs/index.html
Labels: Type-Editorial

#1624 Add dedicated accessibility sections
  epub33/core/index.html
  epub33/rs/index.html
Labels: Cat-Accessibility

#1634 Modification in the RS Appendix A.
  epub33/rs/index.html
Labels: Spec-ReadingSystems

#1639 Add example of source-of to source identification technique
  epub33/a11y-tech/index.html
Labels: Cat-Accessibility
