Repository w3c/epub-specs, pull requests merged in 2021-02, with the labels that each got.

#1495 Change media overlays conformance from a recommendation to requirement
  epub33/a11y/index.html
Labels: Cat-Accessibility

#1498 Add auto value to dir attribute
  epub33/core/index.html
  epub33/rs/index.html
Labels: i18n-tracker

#1510 Adding the "well-formed" requirement for "xml:lang"
  epub33/core/index.html
Labels: Cat-i18n, i18n-tracker

#1511 Draft privacy & security section
  epub33/core/index.html
  epub33/rs/index.html
Labels: Cat-Privacy, Cat-Security

#1519 Consolidate and clean up the scripting section
  epub33/core/index.html
  epub33/rs/index.html
Labels: Cat-Security
