Repository w3c/epub-specs, pull requests merged in 2022-04, with the labels that each got.

#2101 Expand and fix resource explanations
  epub33/a11y/index.html
  epub33/core/index.html
  epub33/overview/index.html
  epub33/reports/exit_criteria.html
  epub33/rs/index.html
Labels: Agenda+

#2137 Remove restriction on mathml deprecated features
  epub33/core/index.html
Labels: Agenda+

#2187 XMLENC-DECRYPT was not a reference
  epub33/rs/index.html
Labels: Type-Editorial

#2191 Improvement of the definition for content plane
  epub33/core/index.html
Labels: Type-Editorial

#2188 Example 65: DigestValue should not be empty
  epub33/core/index.html
Labels: Type-Editorial

#2197 Adding an Oxford Comma
  epub33/core/index.html
Labels: Type-Editorial

#2195 Removed the sentence on "RS MAY optimize..."
  epub33/rs/index.html
Labels: Spec-ReadingSystems, Type-Editorial

#2193 Restructure of section 2 and ocf
  epub33/core/index.html
Labels: Spec-EPUB3, Type-Editorial
