Repository w3c/epub-specs, pull requests merged in 2022-02, with the labels that each got.

#1972 Updated privacy and security sections
  epub33/core/index.html
  epub33/rs/index.html
Labels: Cat-Security, privacy-tracker, Cat-Privacy

#1997 Remove references to closed issues
  epub33/core/index.html
Labels: Type-Editorial

#1998 Removed a reference to obfuscation
  epub33/core/index.html
Labels: Type-Editorial

#1999 Updated the text on FXL and page progression direction
  epub33/rs/index.html
Labels: Type-Editorial

#2000 Made the changes accepted on the WG call for the 'affordance' term
  epub33/a11y/index.html
Labels: Type-Editorial

#2001 Updated the MO text and audio element definitions
  epub33/core/index.html
Labels: Spec-MediaOverlays, Type-Editorial
